# Generated by Django 6.0.2 on 2026-04-22 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_producto_options_alter_producto_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='stock_actual',
        ),
    ]
