# Generated by Django 6.0.2 on 2026-04-27 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_producto_stock_actual_alter_producto_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='unidad_medida',
            field=models.CharField(choices=[('METRO', 'Metro'), ('KG', 'Kilogramo'), ('ROLLO', 'Rollo')], max_length=20),
        ),
    ]
