#Aqui solo es un solo contenedor por que no estamos usando base de datos externa
services:
  usuarios_app:
    build: . #Contruimos en base la carpeta actual
    container_name: usuarios_app #Nombre del contenedor
    ports:
      - "8000:8000"
    volumes:
      - .:/app #Volumen para almacenar los datos
    restart: always #Siempre se reinicia el contenedor si falla
    networks:
      - gestion_lote_net

networks:
  gestion_lote_net:
    external: true