# Generated by Django 6.0.4 on 2026-04-22 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_lote', models.CharField(max_length=25, unique=True)),
                ('producto_id', models.PositiveIntegerField()),
                ('proveedor_id', models.PositiveIntegerField()),
                ('cantidad_inicial', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad_actual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_produccion', models.DateField()),
                ('fecha_entrada', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('REVICION', 'Revisión'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado'), ('AGOTADO', 'Agotado')], default='REVICION', max_length=20)),
            ],
            options={
                'db_table': 'Lote',
                'ordering': ['-fecha_entrada'],
            },
        ),
    ]
