# Generated by Django 6.0.4 on 2026-04-28 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lote',
            name='estado',
            field=models.CharField(choices=[('REVISION', 'Revisión'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado'), ('AGOTADO', 'Agotado')], default='REVICION', max_length=20),
        ),
    ]
