# Generated by Django 6.0.4 on 2026-04-28 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_lote_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lote',
            name='cantidad_actual',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
