# Generated by Django 6.0.4 on 2026-05-13 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_lote_cantidad_actual'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_id', models.PositiveIntegerField()),
                ('tipo', models.CharField(max_length=20)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('destino', models.CharField(blank=True, max_length=100, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='api.lote')),
            ],
            options={
                'db_table': 'Movimiento',
                'ordering': ['-fecha'],
            },
        ),
    ]
