# Generated by Django 6.0.4 on 2026-05-14 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_movimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='destino',
            field=models.CharField(blank=True, choices=[('PRODUCCION', 'Producción'), ('VENTA', 'Venta'), ('DEVOLUCION_PROV', 'Devolución a proveedor'), ('MUESTRA', 'Muestra'), ('COMPRA', 'Compra'), ('INGRESO_ALMACEN', 'Ingreso al almacen')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='tipo',
            field=models.CharField(choices=[('ENTRADA', 'Entrada'), ('SALIDA', 'Salida')], max_length=20),
        ),
    ]
