#Awui solo es un solo servicio por que no estamos usando base de datos externa si no que usamos SQLite
services:
  proveedor_app:
    image: jordany31/proveedor_app:dev #nombre de la imagen para dockerhub
    build: . #Construimos en base de la carpeta actual (De forma local)
    container_name: proveedor_app #Nombre del contenedor
    ports:
      - "8002:8002"
    volumes:
      - .:/app #Volumen para almacenar los datos
    restart: always #Siempre se reinicia el contenedor si falla
    networks:
      - gestion_lote_net

networks:
  gestion_lote_net:
    external: true #Red externa (que ya esta creada)