# Generated by Django 6.0.2 on 2026-04-27 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='telefono',
            field=models.CharField(error_messages={'unique': 'Ya existe un proveedor con ese telefono'}, max_length=15, unique=True),
        ),
    ]
